apiVersion: v1
kind: Service
metadata:
  name: yunjiego-service
  namespace: kangle-control-dev
  labels:
    app: yunjiego-service
spec:
  type: NodePort
  selector:
    app: yunjiego
  ports:
  
  - name: port-8088
    protocol: TCP
    port: 8088 #服务端口, 内部可访问
    targetPort: 8088 #Pod端口
  - name: port-8086
    protocol: TCP
    port: 8086 #服务端口, 内部可访问
    targetPort: 8086 #Pod端口  
